name: AdvancedClans
main: ru.rexlite.AdvancedClans
version: "1.0.2"
author: "Criex (original plugin by: undefined1)"
api: ["1.1.0", "1.0.14"]

commands:
  clan:
    usage: "/clan"
  aclans:
    usage: "/aclans"
    aliases: ["advancedclans"]
